apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ username }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ username }}-rbac
subjects:
- kind: ServiceAccount
  name: {{ username }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
